version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build
      - run: npm run build
      - run:
          name: Create artifacts (zip index.css, index.js, index.php and license.txt)
          command: |
            mkdir ./artifacts
            zip artifacts/build index.* license.txt

      - persist_to_workspace:
          root: ./artifacts
          paths:
            - build.zip

  publish-github-release:

    docker:
      - image: cibuilds/github:0.10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./artifacts

      - run:
          name: "Publish Release on GitHub"
          # You need to create a github token
          # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
          # and store it as GITHUB_TOKEN environment variable in circle ci
          # https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project
          command: |
            echo Creating and releasing ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG}
            mv ./artifacts/build.zip ./artifacts/${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}.zip
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ${CIRCLE_TAG} ./artifacts/



workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
